import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    slug: 'modern-digital-camera',
    name: 'Modern Digital Camera',
    description: "Capture life's moments with stunning clarity and vibrant color.",
    longDescription: "Our Modern Digital Camera features a 24.2MP full-frame sensor, 4K video recording, and a fast hybrid autofocus system. It's lightweight, durable, and perfect for both professionals and enthusiasts. The intuitive touchscreen interface makes it easy to navigate settings and review your shots.",
    price: 1499.99,
    image: 'product-1',
    rating: 4.8,
    reviews: [
      { id: 'r1-1', author: 'Alex P.', rating: 5, text: 'Incredible image quality! Worth every penny.', date: '2023-08-15' },
      { id: 'r1-2', author: 'Sara K.', rating: 4, text: 'Great camera, a bit of a learning curve for beginners.', date: '2023-08-12' },
    ],
    relatedProductIds: ['2', '6', '7'],
  },
  {
    id: '2',
    slug: 'urban-explorer-backpack',
    name: 'Urban Explorer Backpack',
    description: 'A stylish, durable backpack for your daily commute or weekend adventures.',
    longDescription: 'The Urban Explorer Backpack is crafted from water-resistant materials and features multiple compartments, including a padded laptop sleeve that fits up to a 15-inch laptop. Ergonomic shoulder straps ensure comfort, while its minimalist design fits any style.',
    price: 129.99,
    image: 'product-2',
    rating: 4.9,
    reviews: [
      { id: 'r2-1', author: 'John D.', rating: 5, text: 'Perfect for my daily commute. Fits everything I need.', date: '2023-09-01' },
      { id: 'r2-2', author: 'Emily R.', rating: 5, text: 'So stylish and functional. I get compliments everywhere!', date: '2023-08-28' },
    ],
    relatedProductIds: ['4', '7', '10'],
  },
  {
    id: '3',
    slug: 'aero-sound-wireless-headphones',
    name: 'AeroSound Wireless Headphones',
    description: 'Immerse yourself in high-fidelity audio with active noise cancellation.',
    longDescription: 'Experience pure sound with AeroSound. These over-ear headphones offer industry-leading noise cancellation, a 30-hour battery life, and crystal-clear call quality. Plush earcups and a lightweight design provide all-day comfort.',
    price: 349.00,
    image: 'product-3',
    rating: 4.7,
    reviews: [
      { id: 'r3-1', author: 'Mike T.', rating: 5, text: 'The noise cancellation is mind-blowing. It\'s like my own private concert.', date: '2023-09-10' },
    ],
    relatedProductIds: ['7', '4', '1'],
  },
  {
    id: '4',
    slug: 'chronos-smartwatch',
    name: 'Chrono-S Smartwatch',
    description: 'Stay connected and track your fitness goals with this sleek smartwatch.',
    longDescription: 'The Chrono-S features a vibrant AMOLED display, heart rate and blood oxygen monitoring, GPS, and over 100 workout modes. With a 14-day battery life and a premium stainless steel case, it\'s the perfect blend of style and technology.',
    price: 249.50,
    image: 'product-4',
    rating: 4.6,
    reviews: [
      { id: 'r4-1', author: 'Jessica L.', rating: 4, text: 'Love the design, but wish it had more third-party app integrations.', date: '2023-09-05' },
      { id: 'r4-2', author: 'David C.', rating: 5, text: 'Battery life is amazing! Tracks my runs perfectly.', date: '2023-08-20' },
    ],
    relatedProductIds: ['2', '3', '9'],
  },
  {
    id: '5',
    slug: 'sky-voyager-drone',
    name: 'Sky Voyager Drone',
    description: 'Explore the world from a new perspective with our 4K camera drone.',
    longDescription: 'The Sky Voyager is a compact and powerful drone perfect for capturing breathtaking aerial footage. It boasts a 3-axis gimbal for stable 4K video, a 30-minute flight time, and intelligent flight modes like Follow Me and Orbit.',
    price: 799.00,
    image: 'product-5',
    rating: 4.9,
    reviews: [],
    relatedProductIds: ['1', '2', '8'],
  },
  {
    id: '6',
    slug: 'keystroke-pro-mechanical-keyboard',
    name: 'Keystroke Pro Mechanical Keyboard',
    description: 'A satisfying typing experience with customizable RGB backlighting.',
    longDescription: 'Elevate your setup with the Keystroke Pro. Featuring hot-swappable switches, a solid aluminum frame, and fully programmable keys with per-key RGB lighting. It\'s the ultimate keyboard for gamers and coders.',
    price: 189.99,
    image: 'product-6',
    rating: 4.8,
    reviews: [],
    relatedProductIds: ['1', '8', '3'],
  },
  {
    id: '7',
    slug: 'sonic-boom-portable-speaker',
    name: 'SonicBoom Portable Speaker',
    description: 'Take your music anywhere with this rugged, waterproof Bluetooth speaker.',
    longDescription: 'The SonicBoom delivers powerful 360° sound in a compact package. It\'s IP67 waterproof and dustproof, has a 20-hour battery life, and can be paired with another speaker for stereo sound. Your perfect companion for any adventure.',
    price: 99.99,
    image: 'product-7',
    rating: 4.7,
    reviews: [],
    relatedProductIds: ['3', '2', '9'],
  },
  {
    id: '8',
    slug: 'nebula-vr-headset',
    name: 'Nebula VR Headset',
    description: 'Step into new realities with this all-in-one virtual reality system.',
    longDescription: 'The Nebula VR headset offers a truly immersive experience with high-resolution displays, integrated spatial audio, and intuitive controllers. No PC or console required. Explore games, social spaces, and entertainment like never before.',
    price: 399.00,
    image: 'product-8',
    rating: 4.5,
    reviews: [],
    relatedProductIds: ['5', '6', '3'],
  },
  {
    id: '9',
    slug: 'volt-electric-scooter',
    name: 'Volt Electric Scooter',
    description: 'Zip through the city with this fast, foldable electric scooter.',
    longDescription: 'The Volt e-scooter combines performance and portability. It has a top speed of 20 mph, a range of up to 25 miles on a single charge, and a one-step folding system for easy transport and storage. Air-filled tires provide a smooth ride.',
    price: 599.99,
    image: 'product-9',
    rating: 4.6,
    reviews: [],
    relatedProductIds: ['4', '2', '7'],
  },
  {
    id: '10',
    slug: 'ember-smart-mug',
    name: 'Ember Smart Mug',
    description: 'Keep your coffee or tea at the perfect temperature from the first sip to the last.',
    longDescription: 'The Ember Smart Mug allows you to set your precise drinking temperature via a smartphone app. It maintains that temperature for up to 1.5 hours, so your hot beverage is never too hot or too cold. A beautifully designed charging coaster is included.',
    price: 149.95,
    image: 'product-10',
    rating: 4.9,
    reviews: [],
    relatedProductIds: ['2', '4', '6'],
  },
];
